import type {
  Alert,
  AlertRule,
  AreaMoodPoint,
  AppUser,
  Company,
  DashboardSnapshot,
  Employee,
  EmployeeProfile,
  GeographySummary,
  Location,
  MoodCheckin,
  OrgTreeNode,
  OrgUnit,
} from "@/types/app";

export const companies: Company[] = [
  {
    id: "comp-moood-peru",
    name: "MOOOD Andina",
    type: "internal",
    anonymity_mode: "configurable",
  },
  {
    id: "comp-moood-outsourcing",
    name: "MOOOD Field Services",
    type: "external",
    anonymity_mode: "strict",
  },
];

export const locations: Location[] = [
  {
    id: "loc-lima-hq",
    company_id: "comp-moood-peru",
    country: "Peru",
    region: "Lima",
    city: "Lima",
    site_name: "HQ San Isidro",
    lat: -12.0977,
    lng: -77.0365,
  },
  {
    id: "loc-arequipa",
    company_id: "comp-moood-peru",
    country: "Peru",
    region: "Arequipa",
    city: "Arequipa",
    site_name: "Hub Arequipa",
    lat: -16.409,
    lng: -71.5375,
  },
  {
    id: "loc-bogota",
    company_id: "comp-moood-outsourcing",
    country: "Colombia",
    region: "Bogota",
    city: "Bogota",
    site_name: "Operacion Bogota",
    lat: 4.711,
    lng: -74.0721,
  },
  {
    id: "loc-remote",
    company_id: "comp-moood-peru",
    country: "Peru",
    region: "Remoto",
    city: "Remote",
    site_name: "Remote LATAM",
    lat: null,
    lng: null,
  },
];

export const orgUnits: OrgUnit[] = [
  {
    id: "org-company",
    company_id: "comp-moood-peru",
    parent_id: null,
    name: "MOOOD Andina",
    type: "company",
    leader_employee_id: "emp-001",
  },
  {
    id: "org-people",
    company_id: "comp-moood-peru",
    parent_id: "org-company",
    name: "People & Culture",
    type: "division",
    leader_employee_id: "emp-002",
  },
  {
    id: "org-ops",
    company_id: "comp-moood-peru",
    parent_id: "org-company",
    name: "Operations",
    type: "division",
    leader_employee_id: "emp-005",
  },
  {
    id: "org-tech",
    company_id: "comp-moood-peru",
    parent_id: "org-company",
    name: "Product & Data",
    type: "division",
    leader_employee_id: "emp-007",
  },
  {
    id: "org-cx",
    company_id: "comp-moood-peru",
    parent_id: "org-ops",
    name: "Customer Experience",
    type: "team",
    leader_employee_id: "emp-006",
  },
];

export const employees: Employee[] = [
  {
    id: "emp-001",
    company_id: "comp-moood-peru",
    location_id: "loc-lima-hq",
    org_unit_id: "org-company",
    manager_id: null,
    email: "sofia@moood.pe",
    full_name: "Sofia Alvarez",
    role: "super_admin",
    gender: "F",
    job_title: "CEO",
    education: "MBA",
    age: 42,
    tenure_years: 7,
    work_shift: "day",
    occupational_group: "Executive",
    company_type: "internal",
    employment_status: "active",
  },
  {
    id: "emp-002",
    company_id: "comp-moood-peru",
    location_id: "loc-lima-hq",
    org_unit_id: "org-people",
    manager_id: "emp-001",
    email: "camila@moood.pe",
    full_name: "Camila Torres",
    role: "hr_admin",
    gender: "F",
    job_title: "HR Director",
    education: "Bachelor",
    age: 37,
    tenure_years: 4,
    work_shift: "day",
    occupational_group: "People",
    company_type: "internal",
    employment_status: "active",
  },
  {
    id: "emp-003",
    company_id: "comp-moood-peru",
    location_id: "loc-lima-hq",
    org_unit_id: "org-people",
    manager_id: "emp-002",
    email: "lorena@moood.pe",
    full_name: "Lorena Diaz",
    role: "employee",
    gender: "F",
    job_title: "People Analyst",
    education: "Bachelor",
    age: 29,
    tenure_years: 2,
    work_shift: "day",
    occupational_group: "People",
    company_type: "internal",
    employment_status: "active",
  },
  {
    id: "emp-004",
    company_id: "comp-moood-peru",
    location_id: "loc-arequipa",
    org_unit_id: "org-ops",
    manager_id: "emp-005",
    email: "diego@moood.pe",
    full_name: "Diego Ramos",
    role: "employee",
    gender: "M",
    job_title: "Operations Analyst",
    education: "Technical",
    age: 31,
    tenure_years: 1,
    work_shift: "mixed",
    occupational_group: "Operations",
    company_type: "internal",
    employment_status: "active",
  },
  {
    id: "emp-005",
    company_id: "comp-moood-peru",
    location_id: "loc-arequipa",
    org_unit_id: "org-ops",
    manager_id: "emp-001",
    email: "marco@moood.pe",
    full_name: "Marco Escobar",
    role: "leader",
    gender: "M",
    job_title: "Operations Lead",
    education: "Bachelor",
    age: 35,
    tenure_years: 5,
    work_shift: "day",
    occupational_group: "Operations",
    company_type: "internal",
    employment_status: "active",
  },
  {
    id: "emp-006",
    company_id: "comp-moood-peru",
    location_id: "loc-remote",
    org_unit_id: "org-cx",
    manager_id: "emp-005",
    email: "ana@moood.pe",
    full_name: "Ana Vega",
    role: "leader",
    gender: "F",
    job_title: "CX Supervisor",
    education: "Bachelor",
    age: 33,
    tenure_years: 3,
    work_shift: "night",
    occupational_group: "Customer Experience",
    company_type: "internal",
    employment_status: "active",
  },
  {
    id: "emp-007",
    company_id: "comp-moood-peru",
    location_id: "loc-lima-hq",
    org_unit_id: "org-tech",
    manager_id: "emp-001",
    email: "nico@moood.pe",
    full_name: "Nicolas Paredes",
    role: "leader",
    gender: "M",
    job_title: "Head of Product",
    education: "Bachelor",
    age: 34,
    tenure_years: 4,
    work_shift: "day",
    occupational_group: "Technology",
    company_type: "internal",
    employment_status: "active",
  },
  {
    id: "emp-008",
    company_id: "comp-moood-peru",
    location_id: "loc-lima-hq",
    org_unit_id: "org-tech",
    manager_id: "emp-007",
    email: "julio@moood.pe",
    full_name: "Julio Salazar",
    role: "employee",
    gender: "M",
    job_title: "Data Engineer",
    education: "Bachelor",
    age: 28,
    tenure_years: 2,
    work_shift: "day",
    occupational_group: "Technology",
    company_type: "internal",
    employment_status: "active",
  },
];

export const employeeProfiles: EmployeeProfile[] = employees.map((employee) => ({
  employee_id: employee.id,
  phone: "+51 999 000 000",
  bio: `${employee.job_title} en ${employee.full_name.split(" ")[0]}.`,
  request_meeting_default: employee.role === "employee",
}));

export const moodCheckins: MoodCheckin[] = [
  {
    id: "chk-001",
    company_id: "comp-moood-peru",
    employee_id: "emp-003",
    location_id: "loc-lima-hq",
    org_unit_id: "org-people",
    score: 4,
    labels: ["enfocada", "tranquila"],
    note: "Semana estable.",
    anonymous: false,
    request_meeting: false,
    checked_at: "2026-03-17T08:05:00.000Z",
  },
  {
    id: "chk-002",
    company_id: "comp-moood-peru",
    employee_id: "emp-004",
    location_id: "loc-arequipa",
    org_unit_id: "org-ops",
    score: 2,
    labels: ["cansado", "presion"],
    note: "Turno exigente.",
    anonymous: true,
    request_meeting: true,
    checked_at: "2026-03-17T08:30:00.000Z",
  },
  {
    id: "chk-003",
    company_id: "comp-moood-peru",
    employee_id: "emp-006",
    location_id: "loc-remote",
    org_unit_id: "org-cx",
    score: 3,
    labels: ["neutra"],
    note: null,
    anonymous: true,
    request_meeting: false,
    checked_at: "2026-03-17T09:00:00.000Z",
  },
  {
    id: "chk-004",
    company_id: "comp-moood-peru",
    employee_id: "emp-008",
    location_id: "loc-lima-hq",
    org_unit_id: "org-tech",
    score: 5,
    labels: ["motivado", "concentrado"],
    note: "Sprint bien encaminado.",
    anonymous: false,
    request_meeting: false,
    checked_at: "2026-03-17T09:10:00.000Z",
  },
];

export const alertRules: AlertRule[] = [
  {
    id: "ar-001",
    company_id: "comp-moood-peru",
    name: "No marcación 48h",
    type: "marking_missing",
    enabled: true,
    threshold: 2,
    window_days: 2,
  },
  {
    id: "ar-002",
    company_id: "comp-moood-peru",
    name: "Tendencia negativa 7 días",
    type: "negative_trend",
    enabled: true,
    threshold: 3,
    window_days: 7,
  },
];

export const alerts: Alert[] = [
  {
    id: "alt-001",
    company_id: "comp-moood-peru",
    location_id: "loc-arequipa",
    org_unit_id: "org-ops",
    employee_id: null,
    type: "negative_trend",
    status: "open",
    title: "Tendencia negativa en Operaciones",
    detail: "El promedio bajó 0.8 puntos en 7 días.",
    created_at: "2026-03-17T10:00:00.000Z",
  },
  {
    id: "alt-002",
    company_id: "comp-moood-peru",
    location_id: "loc-remote",
    org_unit_id: "org-cx",
    employee_id: null,
    type: "marking_missing",
    status: "sent",
    title: "Baja marcacion en CX",
    detail: "35% del equipo aún no responde el pulso semanal.",
    created_at: "2026-03-17T09:00:00.000Z",
  },
  {
    id: "alt-003",
    company_id: "comp-moood-peru",
    location_id: "loc-arequipa",
    org_unit_id: "org-ops",
    employee_id: "emp-004",
    type: "marking_requested",
    status: "open",
    title: "Solicitud de reunión",
    detail: "Un colaborador pidió reunión con su líder.",
    created_at: "2026-03-17T08:31:00.000Z",
  },
];

export const dashboardSnapshot: DashboardSnapshot = {
  kpis: [
    { label: "Marcaciones hoy", value: "428", delta: "+12% vs ayer", tone: "positive" },
    { label: "Tasa de marcación", value: "84%", delta: "+6 pts", tone: "positive" },
    { label: "Mood ponderado", value: "3.8", delta: "-0.2 pts", tone: "negative" },
    { label: "Anónimo vs identificado", value: "38% / 62%", delta: "Balance saludable", tone: "neutral" },
    { label: "Alertas abiertas", value: "12", delta: "+3 hoy", tone: "negative" },
  ],
  areaMoods: [
    { id: "org-ops", label: "Operations", averageMood: 3.2, weightedScore: 1.91, checkins: 168, employees: 168, participation: 81, weight: 59 },
    { id: "org-company", label: "Direccion General", averageMood: 3.9, weightedScore: 0.75, checkins: 54, employees: 54, participation: 76, weight: 20 },
    { id: "org-tech", label: "Product & Data", averageMood: 4.4, weightedScore: 0.59, checkins: 38, employees: 38, participation: 89, weight: 13 },
    { id: "org-people", label: "People & Culture", averageMood: 4.2, weightedScore: 0.33, checkins: 22, employees: 22, participation: 91, weight: 8 },
  ] satisfies AreaMoodPoint[],
  timeSeries: [
    { date: "2026-03-11", mood: 4.1, checkins: 350 },
    { date: "2026-03-12", mood: 4.0, checkins: 368 },
    { date: "2026-03-13", mood: 3.8, checkins: 389 },
    { date: "2026-03-14", mood: 3.9, checkins: 332 },
    { date: "2026-03-15", mood: 3.7, checkins: 301 },
    { date: "2026-03-16", mood: 3.9, checkins: 412 },
    { date: "2026-03-17", mood: 3.8, checkins: 428 },
  ],
  scoreDistribution: [
    { label: "1", value: 18 },
    { label: "2", value: 42 },
    { label: "3", value: 120 },
    { label: "4", value: 176 },
    { label: "5", value: 72 },
  ],
  byGender: [
    { label: "F", value: 4.1 },
    { label: "M", value: 3.6 },
    { label: "X", value: 3.8 },
  ],
  byLocation: [
    { label: "HQ Lima", value: 4.2 },
    { label: "Arequipa", value: 3.1 },
    { label: "Bogota", value: 3.7 },
    { label: "Remote", value: 3.5 },
  ],
  byJobTitle: [
    { label: "Analistas", value: 3.6 },
    { label: "Supervisores", value: 3.4 },
    { label: "Jefaturas", value: 4.1 },
    { label: "Dirección", value: 4.3 },
  ],
  byEducation: [
    { label: "Técnico", value: 3.3 },
    { label: "Bachelor", value: 3.8 },
    { label: "MBA", value: 4.4 },
  ],
  byTenure: [
    { label: "0-1 años", value: 3.5 },
    { label: "2-4 años", value: 3.9 },
    { label: "5+ años", value: 4.2 },
  ],
  byOccupationalGroup: [
    { label: "People", value: 4.2 },
    { label: "Operations", value: 3.1 },
    { label: "CX", value: 3.4 },
    { label: "Technology", value: 4.4 },
  ],
  byCompanyType: [
    { label: "Interna", value: 3.9 },
    { label: "Externa", value: 3.4 },
  ],
  detailedRows: [
    {
      id: "row-1",
      date: "2026-03-17 08:05",
      employee: "Lorena Diaz",
      location: "HQ San Isidro",
      orgUnit: "People & Culture",
      score: 4,
      anonymous: false,
    },
    {
      id: "row-2",
      date: "2026-03-17 08:30",
      employee: "Anonimizado",
      location: "Hub Arequipa",
      orgUnit: "Operations",
      score: 2,
      anonymous: true,
    },
    {
      id: "row-3",
      date: "2026-03-17 09:10",
      employee: "Julio Salazar",
      location: "HQ San Isidro",
      orgUnit: "Product & Data",
      score: 5,
      anonymous: false,
    },
  ],
};

export const geographySummary: GeographySummary[] = [
  {
    id: "loc-lima-hq",
    name: "HQ San Isidro",
    country: "Peru",
    region: "Lima",
    city: "Lima",
    averageMood: 4.2,
    employees: 120,
    alerts: 2,
    lat: -12.0977,
    lng: -77.0365,
  },
  {
    id: "loc-arequipa",
    name: "Hub Arequipa",
    country: "Peru",
    region: "Arequipa",
    city: "Arequipa",
    averageMood: 3.1,
    employees: 82,
    alerts: 5,
    lat: -16.409,
    lng: -71.5375,
  },
  {
    id: "loc-bogota",
    name: "Operacion Bogota",
    country: "Colombia",
    region: "Bogota",
    city: "Bogota",
    averageMood: 3.7,
    employees: 56,
    alerts: 2,
    lat: 4.711,
    lng: -74.0721,
  },
  {
    id: "loc-remote",
    name: "Remote LATAM",
    country: "Peru",
    region: "Remoto",
    city: "Remote",
    averageMood: 3.5,
    employees: 24,
    alerts: 1,
    lat: null,
    lng: null,
  },
];

export const orgTree: OrgTreeNode = {
  id: "org-company",
  name: "MOOOD Andina",
  type: "Company",
  leader: "Sofia Alvarez",
  collaborators: 282,
  averageMood: 3.8,
  children: [
    {
      id: "org-people",
      name: "People & Culture",
      type: "Division",
      leader: "Camila Torres",
      collaborators: 22,
      averageMood: 4.2,
      children: [],
    },
    {
      id: "org-ops",
      name: "Operations",
      type: "Division",
      leader: "Marco Escobar",
      collaborators: 168,
      averageMood: 3.2,
      children: [
        {
          id: "org-cx",
          name: "Customer Experience",
          type: "Team",
          leader: "Ana Vega",
          collaborators: 68,
          averageMood: 3.4,
          children: [],
        },
      ],
    },
    {
      id: "org-tech",
      name: "Product & Data",
      type: "Division",
      leader: "Nicolas Paredes",
      collaborators: 38,
      averageMood: 4.4,
      children: [],
    },
  ],
};

export const currentMockUser: AppUser = {
  id: "emp-002",
  email: "camila@moood.pe",
  full_name: "Camila Torres",
  role: "hr_admin",
  company_id: "comp-moood-peru",
  org_unit_id: "org-people",
};

